name: Test-all
on: push
jobs:
  test-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setting up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Testing with gradle
        uses: gradle/gradle-build-action@v2
      - run: ./gradlew clean test

