name: Test-all
on: push
jobs:
	test-all:
	   runs-on: ubuntu-latest
	   steps:
		- uses: actions/checkout@v3
		- name: Setting up JDK 11
		  uses: actions/setup-java@v3
		  with:
		    java-version: '11'
		    distribution: 'temurin'
		- name: Testing with gradle
		  uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
		  with:
		    arguments: clean test